#:schema node_modules/wrangler/config-schema.json
name = "yaibot"
main = "src/index.ts"
compatibility_date = "2025-11-17"
minify = true
upload_source_maps = true
workers_dev = false

[[d1_databases]]
binding = "DB"
database_id = "a500a82a-8339-47bb-9d52-7e23ac022dca"
database_name = "luojokesbot_db"

[vars.BOT_INFO]
id = 8233852686
is_bot = true
first_name = "罗老师语录"
username = "luojokesbot"
can_join_groups = true
can_read_all_group_messages = false
supports_inline_queries = true
can_connect_to_business = false
has_main_web_app = false
